### ISSUE TITLE
People Picker

### ISSUE THREAD

**Issue by chanm003** [chanm003/airsupport#2]
- [x] should query user directory #7 

- [x] should search as user types (auto-complete) and only be able to pick an item that comes back from query results #10

- [x] querying user directory should not be case sensitive #9
